project:
  type: website

website:
  title: "Health & Food"
  navbar:
    left:
      - href: index.qmd
        text: Overview
      - href: health-food.qmd
        text: Health & Food
      - href: food.qmd
        text: About

format:
  html:
    theme: lux
    toc: false

execute:
  echo: false
  warning: false
  message: false

